[project]
name = "chip8emu"
version = "0.1.0"
description = "A CHIP-8 interpreter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "mypy>=1.17.1",
]
